server:
  port: 9001

project:
  ip: 127.0.0.1

spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${project.ip}:8848
      config:
        file-extension: yaml
        server-addr: ${project.ip}:8848
        group: DEFAULT_GROUP

dubbo:
  scan:
    base-packages: com.mine.dubboprovider.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://${project.ip}
