server:
  port: 9101

spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: dubbo-provider
