server:
  port: 9101


project:
  ip: 127.0.0.1

spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: ${project.ip}:8848
      config:
        file-extension: yaml
        server-addr: ${project.ip}:8848
        group: DEFAULT_GROUP

dubbo:
  registry:
    address: spring-cloud://${project.ip}
  cloud:
    subscribed-services: dubbo-provider
